# Generated by Django 4.2.7 on 2023-11-28 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('max_number_participants', models.IntegerField(verbose_name='maximum number of participants')),
                ('category', models.CharField(max_length=255)),
            ],
        ),
    ]
